config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    resources :currencies
  end

  scope :module => :web do
    root to: 'welcome#index'


    namespace :admin do
      root to: 'currencies#index'

      resources :currencies

    end

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
  has_many :currency_histories

  serialize :data

  #validates :name, presence: true, uniqueness: true
  validates :rate, presence: true, numericality: {:greater_than_or_equal_to => 0}
  #validates :forced_date, presence: true
  #validate :forced_date_after_now


  state_machine :state, :initial => :auto do
    state :auto
    state :manual

    event :automatically do
      transition all => :auto
    end

    event :manually do
      transition all => :manual
    end
  end


  def to_s
    name
  end



  private

  def forced_date_after_now
    return if forced_date.blank?

    if forced_date < Time.now.utc
      errors.add(:forced_date, I18n.t('activerecord.errors.models.currency.attributes.forced_date.in_past'))
    end
 end

end

app/models/currency_history.rb
class CurrencyHistory < ApplicationRecord
  belongs_to :currency
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
  #respond_to :json
end

app/controllers/api/currencies_controller.rb
class Api::CurrenciesController < Api::ApplicationController

  def index
    @currency = Currency.first
  end


  private

  def permit_params
    params.require(:currency).permit(:name, :rate, :forced_date, :state, :updated_at)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/web/admin/application_controller.rb
class Web::Admin::ApplicationController < Web::ApplicationController

end

app/controllers/web/admin/currencies_controller.rb
class Web::Admin::CurrenciesController < Web::Admin::ApplicationController

  def index
    @currency = Currency.first
  end


  def update
    @currency = Currency.find(params[:id])
    if @currency.update_attributes(permit_params)
       @currency.manually

      flash[:success] = t("message.updated")

      redirect_to admin_root_path
    else
      flash[:alert] = @currency.errors.full_messages

      render :index
    end
  end


  private

  def permit_params
    params.require(:currency).permit(:name, :rate, :forced_date, :state, :updated_at)
  end



end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  
end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController

   def index
     #@currency = Currency.first
   end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_html_safe str
		return if str.nil?

		Sanitize.fragment(str, Sanitize::Config::BASIC).html_safe
	end


  def flash_class level
      case level
      when 'notice' then "alert alert-primary"
          when 'success' then "alert alert-success"
          when 'warning' then "alert alert-warning"
          when 'error' then "alert alert-danger"
          when 'alert' then "alert alert-danger"
      end
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CurrencyRateService
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      %nav.navbar.navbar-dark.bg-dark.fixed-top
        .container
          = link_to 'RateService', root_path, class: "navbar-brand"
    %main.container
      = render 'layouts/partial/flashes'
      = yield
  %footer.footer
    .container
      = link_to "Курсы ЦБ РФ в XML и JSON, API", "#", class: "text-muted", onclick: "window.open('https://www.cbr-xml-daily.ru/');return false;"

app/views/layouts/partial/_flashes.html.haml
- flash.each do |name, msg|
  - if msg.kind_of?(Array)
    %div{class: flash_class(name)}
      = content_tag :div, flash_html_safe(msg.join("<br/>"))
  - else
    %div{class: flash_class(name)}
      = content_tag :div, flash_html_safe(msg)

app/views/web/admin/currencies/_form.html.haml
= simple_form_for @currency, url: admin_currency_path(@currency), html: {novalidate: true}  do |f|
  -#.form-group
    = f.input :name, input_html: {class: 'form-control '}
  .form-group
    = f.input :rate, input_html: {class: 'form-control'}
  .form-group
    = f.input :forced_date, as: :string, input_html: {class: 'form-control datepicker'}
  -#.form-group
    = f.input :state, collection: @currency.state_paths.to_states, include_blank: false

  .form-group
    = f.submit "Save", class: "btn btn-success"
    = link_to "Cancel", admin_root_path, class: "btn btn-info"

app/views/web/admin/currencies/index.html.haml
= render "form"

app/views/web/welcome/index.html.haml
= react_component("App")